Hw03 frequency analysis
maxim-panchuk/otus pull request #3
Opened 2024-09-12 09:50 UTC by maxim-panchuk

2024-09-12 11:17 UTC, vladislavmass requested changes
Хорошее начало, но без новых тестов принять не могу

2024-09-12 11:17 UTC, vladislavmass commented on hw03_frequency_analysis/top.go
> +		if i >= len(wordFreq) {
Подскажите на какой кейс рассчитан этот вариант? Данный код выглядит недостижимым

2024-09-15 18:23 UTC, maxim-panchuk commented
Добавил тесты

2024-09-16 03:03 UTC, vladislavmass approved these changes

2024-09-16 07:15 UTC, merged